//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECT_LIST
    {
        public System.Guid Id { get; set; }
        public int ObjectId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string SurveyType { get; set; }
        public string GroupName { get; set; }
        public int Key { get; set; }
        public string ObjectType { get; set; }
        public int kodTPP { get; set; }
        public Nullable<int> kodCEH { get; set; }
        public Nullable<int> kodPLOT { get; set; }
        public Nullable<int> kodMST { get; set; }
        public string Title { get; set; }
        public int RangeNumber { get; set; }
        public string Formula { get; set; }
        public bool Itog { get; set; }
        public string Alignment { get; set; }
        public string FontWeight { get; set; }
        public string FontStyle { get; set; }
        public bool InList { get; set; }
        public System.DateTime Created { get; set; }
        public string Author { get; set; }
        public System.DateTime LastSaved { get; set; }
        public string LastEditor { get; set; }
        public int ObjectKod { get; set; }
    }
}
