//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RABOTY_DEVELOPMENT_COMMON
    {
        public System.Guid Id { get; set; }
        public System.Guid SkvId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string Contractor { get; set; }
        public string Master { get; set; }
        public Nullable<int> Account { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> NumberInPosition { get; set; }
        public Nullable<int> WaitingCount { get; set; }
        public Nullable<double> WaitingDebit { get; set; }
        public Nullable<double> ProjectDepth { get; set; }
        public string ProjectLevel { get; set; }
        public Nullable<System.DateTime> DevelopStartDatePlan { get; set; }
        public Nullable<System.DateTime> DevelopStartDateFact { get; set; }
        public Nullable<System.DateTime> DevelopFinishDatePlan { get; set; }
        public Nullable<System.DateTime> DevelopFinishDateFact { get; set; }
        public Nullable<System.DateTime> ImplementDatePlan { get; set; }
        public Nullable<System.DateTime> ImplementDateFact { get; set; }
        public string PerfInterval { get; set; }
        public Nullable<double> NormoTime { get; set; }
        public Nullable<System.DateTime> ActDate { get; set; }
        public string ContinueOnPlan { get; set; }
        public Nullable<double> CommonTime { get; set; }
        public Nullable<double> NonNormoTime { get; set; }
        public System.DateTime Created { get; set; }
        public string Author { get; set; }
        public System.DateTime LastSaved { get; set; }
        public string LastEditor { get; set; }
    }
}
