//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RABOTY_DEVELOPMENT_WORKS
    {
        public System.Guid Id { get; set; }
        public System.Guid CommonId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> Face { get; set; }
        public Nullable<double> Drift { get; set; }
        public Nullable<double> Duration { get; set; }
        public string Work { get; set; }
        public System.DateTime Created { get; set; }
        public string Author { get; set; }
        public System.DateTime LastSaved { get; set; }
        public string LastEditor { get; set; }
    }
}
