//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RITEK_WEBEntities : DbContext
    {
        public RITEK_WEBEntities()
            : base("name=RITEK_WEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<hp_PlanOperNFT_Result> hp_PlanOperNFT(Nullable<decimal> kodTPP)
        {
            var kodTPPParameter = kodTPP.HasValue ?
                new ObjectParameter("kodTPP", kodTPP) :
                new ObjectParameter("kodTPP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_PlanOperNFT_Result>("hp_PlanOperNFT", kodTPPParameter);
        }
    }
}
