//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKV_NSI
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public Nullable<int> BushId { get; set; }
        public Nullable<int> kodMST { get; set; }
        public Nullable<int> kodSKV { get; set; }
        public Nullable<int> RangeNumber { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StadeDate { get; set; }
        public Nullable<int> StadeId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PurposeId { get; set; }
        public string Regime { get; set; }
        public string Geo { get; set; }
        public string GNO { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<double> Qzh { get; set; }
        public Nullable<double> Percent { get; set; }
        public Nullable<double> Qn { get; set; }
        public Nullable<double> Ndin { get; set; }
        public string ExplMethod { get; set; }
        public string NOstrov { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
