//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STANDARD_PARAMETERS
    {
        public System.Guid Id { get; set; }
        public string ParamName { get; set; }
        public string Title { get; set; }
        public string Header { get; set; }
        public string Formula1 { get; set; }
        public string Formula2 { get; set; }
        public int RangeNumber { get; set; }
    }
}
