//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPERHEADERS
    {
        public int Id { get; set; }
        public string SurveyType { get; set; }
        public string GroupName { get; set; }
        public int RangeNumber { get; set; }
        public int ColumnsCount { get; set; }
        public string Header { get; set; }
    }
}
