//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public System.Guid Id { get; set; }
        public string SurveyType { get; set; }
        public string groupName { get; set; }
        public System.DateTime Date { get; set; }
        public string ObjectType { get; set; }
        public int ObjectKod { get; set; }
        public int Key { get; set; }
        public Nullable<double> Plan { get; set; }
        public Nullable<double> Graphic { get; set; }
        public Nullable<double> Fact { get; set; }
        public Nullable<int> SourceType { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public System.DateTime Created { get; set; }
        public string Author { get; set; }
        public System.DateTime LastSaved { get; set; }
        public string LastEditor { get; set; }
        public Nullable<double> Param1 { get; set; }
        public Nullable<double> Param2 { get; set; }
        public Nullable<double> Param3 { get; set; }
        public Nullable<double> Param4 { get; set; }
        public Nullable<double> Param5 { get; set; }
        public Nullable<double> Param6 { get; set; }
        public Nullable<double> Param7 { get; set; }
        public Nullable<double> Param8 { get; set; }
        public Nullable<double> Param9 { get; set; }
        public Nullable<double> Param10 { get; set; }
        public Nullable<double> Param11 { get; set; }
        public Nullable<double> Param12 { get; set; }
        public Nullable<double> Param13 { get; set; }
        public Nullable<double> Param14 { get; set; }
        public Nullable<double> Param15 { get; set; }
        public Nullable<double> Param16 { get; set; }
        public Nullable<double> Param17 { get; set; }
        public Nullable<double> Param18 { get; set; }
        public Nullable<double> Param19 { get; set; }
        public Nullable<double> Param20 { get; set; }
        public Nullable<double> Param21 { get; set; }
        public Nullable<double> Param22 { get; set; }
        public Nullable<double> Param23 { get; set; }
        public Nullable<double> Param24 { get; set; }
        public Nullable<double> Param25 { get; set; }
        public Nullable<double> Param26 { get; set; }
        public Nullable<double> Param27 { get; set; }
        public Nullable<double> Param28 { get; set; }
        public Nullable<double> Param29 { get; set; }
        public Nullable<double> Param30 { get; set; }
        public string Comment3 { get; set; }
        public string Comment4 { get; set; }
        public string Comment5 { get; set; }
        public string Comment6 { get; set; }
        public string Comment7 { get; set; }
    }
}
