//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECH_OBJ_NSI
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Type { get; set; }
        public int kodCEH { get; set; }
        public Nullable<int> kodPLOT { get; set; }
    }
}
